- name: OBTENDO DOCKER SCRIPTS PARA INSTALACAO
  get_url:
    url: "{{ url_docker_script }}"
    dest: "{{ dst_docker_script }}"
    mode: '0755'  
  register: download_script

- name: IMPLANTANDO O DOCKER 
  command: "{{ dst_docker_script }}"
  when: download_script
  notify: Restart Docker
  register: instalando_docker

- name: ELIMINANDO ARQUIVOS SCRIPT DE CONFIGURACAO
  file:
    path: "{{ dst_docker_script }}"
    state: absent
  register: removendo_script

- name: CONFIGURANDO REPO E AS CHAVES PARA K8S
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: CONFIGURANDO O REPO DO KUBERNETES
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: IMPLANTANDO OS PACOTES KUBEADM, KUBELET e KUBECTL
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet=1.20.0-00 
    - kubeadm=1.20.0-00 
    - kubectl=1.20.0-00
  notify: Restart Kubelet

