---
- name: OBTENDO HELM CHARTS MANAGER
  get_url: 
    url: "{{ helm_url }}" 
    dest: /tmp/get_helm.sh
    mode: 0775
  ignore_errors: true 
  register: download

- name: IMPLANTANDO E CONFIGURANDO HELM PACKAGE
  command: /tmp/get_helm.sh
  when: download
  register: install_helm

- name: CONFIGURANDO VARIAVEIS PARA HELM
  debug: var=install_helm
