apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-stag
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: staging.caboverde-vendas-prod.xyz
      http:
        paths:
          - path: /api/payments/?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: payments-srv-stag
                port:
                  number: 3000
          - path: /api/users/?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: auth-srv-stag
                port:
                  number: 3000
          - path: /api/tickets/?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: tickets-srv-stag
                port:
                  number: 3000
          - path: /api/orders/?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: orders-srv-stag
                port:
                  number: 3000
          - path: /?(.*)
            pathType: 'Prefix'
            backend:
              service:
                name: client-srv-stag
                port:
                  number: 3000
                  
