apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis-stag
  template:
    metadata:
      labels:
        app: expiration-redis-stag
    spec:
      containers:
        - name: expiration-redis-stag
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv-stag
  namespace: staging
spec:
  selector:
    app: expiration-redis-stag
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
