apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-stag
  template:
    metadata:
      labels:
        app: nats-stag
    spec:
      containers:
        - name: nats-stag
          image: nats-streaming:0.17.0
          args:
            [
              '-p',
              '4222',
              '-m',
              '8222',
              '-hbi',
              '5s',
              '-hbt',
              '5s',
              '-hbf',
              '2',
              '-SD',
              '-cid',
              'ticketing',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv-stag
  namespace: staging
spec:
  selector:
    app: nats-stag
  ports:
    - name: client-stag
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring-stag
      protocol: TCP
      port: 8222
      targetPort: 8222
