apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo-stag
  template:
    metadata:
      labels:
        app: orders-mongo-stag
    spec:
      containers:
        - name: orders-mongo-stag
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv-stag
  namespace: staging
spec:
  selector:
    app: orders-mongo-stag
  ports:
    - name: db-stag
      protocol: TCP
      port: 27017
      targetPort: 27017
