- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'PRE TASKS - ATUALIZANDO OS REPOSITORIOS'
    raw: 'apt-get update'
    changed_when: False
  - name: 'PRE TASKS - IMPLANTANDO PYTHON 3'
    raw: 'apt-get install -y python'
    register: install_python
    changed_when: '"Setting up python" in install_python.stdout'
  - name: 'PRE TASKS - IMPLANTANDO_STRESS'
    raw: 'apt-get install stress'
    register: install_stress
    changed_when: '"Setting up python" in install_stress.stdout'
  roles:
  - { role: instalar_config_kubernetes, tags: ["instalar_config_kubernetes_role"]  } 

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: criar_config_cluster, tags: ["criar_config_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - { role: config_cluster_workers, tags: ["config_cluster_workers_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles: 
  - { role: instalar_config_helm_charts, tags: ["instalar_config_helm_charts_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles: 
  - { role: instalar_config_monitors, tags: ["instalar_config_monitors_role"] }
