- name: ADICIONANDO REPOSITORIOS HELM
  command: helm repo add stable {{ url_repo_helm }}
  register: prometheus_add_repo
  changed_when: '"been added to" in prometheus_add_repo.stdout'

- name: ATUALIZANDO OS REPO HELM
  command: helm repo update
  register: prrometheus_repo_update
  changed_when: '"Update Complete" in prrometheus_repo_update.stdout'

- name: IMPLANTANDO O PROMETHEUS OPERATOR PELO HELM
  command: helm install {{ deploy_prometheus }}
  register: prometheus_install
  changed_when: True

- name: UPLOADS ALERTS FILES CONFIG
  become: true 
  copy:
    src: /home/stevenalves/Desktop/caboverde-vendas-devops/alerts
    dest: /home/ubuntu
    owner: root
    group: root
    mode: '0644'

- name: DELETE OLD CONFIG ALERTS
  become: true 
  command: kubectl delete secret alertmanager-prometheus-monitor-prometh-alertmanager
  register: deleting_secret_alertmanager
  changed_when: '"Update Complete" in deleting_secret_alertmanager.stdout'

- name: CREATE CONFIG ALERTS
  become: true 
  command: kubectl create secret generic --from-file=/home/ubuntu/alerts/alertmanager.yaml alertmanager-prometheus-monitor-prometh-alertmanager
  register: create_secret_alertmanager
  changed_when: '"Update Complete" in create_secret_alertmanager.stdout'
