- name: ADICIONANDO REPOSITORIOS HELM
  command: helm repo add stable {{ url_repo_helm }}
  register: prometheus_add_repo
  changed_when: '"been added to" in prometheus_add_repo.stdout'

- name: ATUALIZANDO OS REPO HELM
  command: helm repo update
  register: prrometheus_repo_update
  changed_when: '"Update Complete" in prrometheus_repo_update.stdout'

- name: IMPLANTANDO O PROMETHEUS OPERATOR PELO HELM
  command: helm install {{ deploy_prometheus }}
  register: prometheus_install
  changed_when: True