apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-stag
  template:
    metadata:
      labels:
        app: auth-stag
    spec:
      containers:
        - name: auth-stag
          image: 5120/auth-stag
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv-stag:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv-stag
  namespace: staging
spec:
  selector:
    app: auth-stag
  ports:
    - name: auth-stag
      protocol: TCP
      port: 3000
      targetPort: 3000
