apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-stag
  template:
    metadata:
      labels:
        app: client-stag
    spec:
      containers:
        - name: client-stag
          image: 5120/client-stag
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv-stag
  namespace: staging 
spec:
  selector:
    app: client-stag
  ports:
    - name: client-stag
      protocol: TCP
      port: 3000
      targetPort: 3000
