apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-stag
  template:
    metadata:
      labels:
        app: orders-stag
    spec:
      containers:
        - name: orders-stag
          image: 5120/orders-stag
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv-stag:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv-stag:27017/orders'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv-stag
  namespace: staging
spec:
  selector:
    app: orders-stag
  ports:
    - name: orders-stag
      protocol: TCP
      port: 3000
      targetPort: 3000
