apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl-stag
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-stag
  template:
    metadata:
      labels:
        app: payments-stag
    spec:
      containers:
        - name: payments-stag
          image: 5120/payments-stag
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv-stag:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv-stag:27017/payments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv-stag
  namespace: staging
spec:
  selector:
    app: payments-stag
  ports:
    - name: payments-stag
      protocol: TCP
      port: 3000
      targetPort: 3000
