- name: MOSTRANDO OS TOKEN E CONFIGURAR OS WORKER
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - O TOKEN: {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name: MOSTRANDO OS HASH PARA CONFIGURACAO DOS WORKERS
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - O HASH: {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: RESETANDO O CLUSTER
  command: 
    kubeadm reset --force
  register: kubeadm_reset
  changed_when: '"Deleting contents" in kubeadm_reset.stdout'

- name: CONFIGURANDO OS WORKERS E CLUSTER KUBERNETES
  shell:
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} 
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} 
    {{ K8S_MASTER_NODE_IP }}:{{ K8S_API_SECURE_PORT }}
  register: add_worker
  changed_when: '"This node has joined the cluster" in add_worker.stdout'
