name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.K8S_AWS }}
          version: v1.21.0 
          command: apply -f infra/k8s && kubectl apply -f infra/k8s-prod
          
