name: tests-payments

on:
  pull_request:
    paths:
      - 'e2e/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd e2e && npm install && npm run test:ci
