name: tests-payments

on:
  pull_request:
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd infra && npm install && npm run test:ci
