name: tests-payments

on:
  pull_request:
    paths:
      - 'load-tests/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd load-tests && npm install && npm run test:ci
